<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class PhoneNumbersViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_phone_numbers_view()
    {
        $response = $this->get('sms/phone-numbers');

        $response->assertStatus(200)->assertViewIs('SMS::phone_numbers.index');
    }

    public function test_phone_numbers_create()
    {
        $response = $this->get('sms/phone-numbers/create');

        $response->assertViewIs('SMS::phone_numbers.create_edit')->assertStatus(200);
    }
}
